/*
 * GoAstra CLI - GraphQL Schema Template
 *
 * Generates the GraphQL schema definition file.
 * Provides base types for User, Auth, and pagination.
 */
package graphql

// SchemaGraphQL returns the schema.graphqls template.
func SchemaGraphQL() string {
	return `# GoAstra GraphQL Schema
# Generated by GoAstra CLI
#
# This is the main schema file. Add your types, queries, and mutations here.
# Run 'go generate ./...' after making changes to regenerate the Go code.

# ============================================================================
# QUERIES
# ============================================================================

type Query {
  """Health check endpoint"""
  health: Health!

  """Get current authenticated user"""
  me: User

  """Get a user by ID"""
  user(id: ID!): User

  """List users with pagination"""
  users(page: Int = 1, pageSize: Int = 20): UserConnection!
}

# ============================================================================
# MUTATIONS
# ============================================================================

type Mutation {
  """Register a new user account"""
  register(input: RegisterInput!): AuthPayload!

  """Login with email and password"""
  login(input: LoginInput!): AuthPayload!

  """Refresh access token"""
  refreshToken(refreshToken: String!): AuthPayload!

  """Logout and invalidate tokens"""
  logout: Boolean!

  """Update current user profile"""
  updateProfile(input: UpdateProfileInput!): User!

  """Create a new user (admin only)"""
  createUser(input: CreateUserInput!): User!

  """Update a user (admin only)"""
  updateUser(id: ID!, input: UpdateUserInput!): User!

  """Delete a user (admin only)"""
  deleteUser(id: ID!): Boolean!
}

# ============================================================================
# TYPES
# ============================================================================

"""Health check response"""
type Health {
  status: String!
  database: String!
  version: String!
}

"""User account"""
type User {
  id: ID!
  email: String!
  name: String!
  role: String!
  active: Boolean!
  createdAt: String!
  updatedAt: String!
}

"""Paginated list of users"""
type UserConnection {
  data: [User!]!
  total: Int!
  page: Int!
  pageSize: Int!
  totalPages: Int!
}

"""Authentication response with tokens"""
type AuthPayload {
  token: String!
  refreshToken: String!
  expiresAt: Int!
  user: User!
}

# ============================================================================
# INPUTS
# ============================================================================

"""Login credentials"""
input LoginInput {
  email: String!
  password: String!
}

"""Registration data"""
input RegisterInput {
  email: String!
  password: String!
  name: String!
}

"""Profile update data"""
input UpdateProfileInput {
  name: String
  email: String
  password: String
}

"""User creation data (admin)"""
input CreateUserInput {
  email: String!
  password: String!
  name: String!
  role: String
}

"""User update data (admin)"""
input UpdateUserInput {
  email: String
  name: String
  role: String
  active: Boolean
}
`
}
