/*
 *  * AuthTokens contains authentication token pair.
 * Auto-generated by GoAstra typesync
 */

export interface AuthTokens {
  access_token: string;
  refresh_token: string;
  expires_in: number;
  token_type: string;
}
