/*
 *  * BaseModel provides common fields for all database models.
 * Automatically handles ID, timestamps, and soft deletes.
 * Auto-generated by GoAstra typesync
 */

export interface BaseModel {
  id: number;
  created_at: string;
  updated_at: string;
}
