/*
 *  * PaginatedResponse wraps list responses with pagination metadata.
 * Auto-generated by GoAstra typesync
 */

export interface PaginatedResponse {
  data: unknown;
  total: number;
  page: number;
  page_size: number;
  total_pages: number;
}
