/*
 *  * UserProfile represents publicly visible user information.
 * Auto-generated by GoAstra typesync
 */

export interface UserProfile {
  id: number;
  name: string;
  avatar?: string;
  bio?: string;
}
