/*
 *  * User represents an authenticated user in the system.
 * Auto-generated by GoAstra typesync
 */

export interface User {
  email: string;
  name: string;
  role: string;
  active: boolean;
  avatar?: string;
}
