/*
 * GoAstra CLI - Ent Generator
 *
 * Generates Ent ORM schema definitions for new entities.
 * Creates schema files with fields, edges, and indexes.
 */
package generator

import (
	"fmt"
	"os"
	"path/filepath"
)

/*
 * EntGenerator handles Ent schema generation.
 */
type EntGenerator struct {
	name       string
	pascalName string
	camelName  string
	snakeName  string
}

/*
 * NewEntGenerator creates a new Ent generator instance.
 */
func NewEntGenerator(name string) *EntGenerator {
	return &EntGenerator{
		name:       name,
		pascalName: toPascalCase(name),
		camelName:  toCamelCase(name),
		snakeName:  toSnakeCase(name),
	}
}

/*
 * GenerateSchema creates an Ent schema file for the entity.
 */
func (g *EntGenerator) GenerateSchema() error {
	content := fmt.Sprintf(`package schema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

/*
 * %s holds the schema definition for the %s entity.
 * Generated by GoAstra CLI
 */
type %s struct {
	ent.Schema
}

/*
 * Fields of the %s entity.
 */
func (%s) Fields() []ent.Field {
	return []ent.Field{
		// TODO: Add your fields here
		//
		// Example fields:
		// field.String("name").
		//     NotEmpty().
		//     Comment("%s name"),
		//
		// field.String("description").
		//     Optional().
		//     Comment("%s description"),
		//
		// field.Int("quantity").
		//     Default(0).
		//     NonNegative().
		//     Comment("Quantity in stock"),
		//
		// field.Float("price").
		//     Positive().
		//     Comment("Price in USD"),
		//
		// field.Bool("active").
		//     Default(true).
		//     Comment("Whether the %s is active"),
		//
		// field.Enum("status").
		//     Values("pending", "active", "archived").
		//     Default("pending").
		//     Comment("%s status"),

		field.Time("created_at").
			Default(time.Now).
			Immutable().
			Comment("Creation timestamp"),

		field.Time("updated_at").
			Default(time.Now).
			UpdateDefault(time.Now).
			Comment("Last update timestamp"),
	}
}

/*
 * Edges of the %s entity.
 * Define relationships to other entities here.
 *
 * Example edges:
 *
 * func (%s) Edges() []ent.Edge {
 *     return []ent.Edge{
 *         // One-to-many: %s belongs to a User
 *         edge.From("owner", User.Type).
 *             Ref("%ss").
 *             Unique(),
 *
 *         // Many-to-many: %s has many Tags
 *         edge.To("tags", Tag.Type),
 *     }
 * }
 */
func (%s) Edges() []ent.Edge {
	return nil
}

/*
 * Indexes of the %s entity.
 */
func (%s) Indexes() []ent.Index {
	return []ent.Index{
		// TODO: Add indexes for frequently queried fields
		//
		// Example indexes:
		// index.Fields("name"),
		// index.Fields("status"),
		// index.Fields("created_at"),
		//
		// Composite index:
		// index.Fields("status", "created_at"),
		//
		// Unique index:
		// index.Fields("email").Unique(),
	}
}

/*
 * Mixin allows embedding common fields across schemas.
 * Uncomment to use timestamps mixin instead of explicit fields.
 *
 * func (%s) Mixin() []ent.Mixin {
 *     return []ent.Mixin{
 *         TimestampsMixin{},
 *     }
 * }
 */
`,
		g.pascalName, g.pascalName,
		g.pascalName,
		g.pascalName,
		g.pascalName,
		g.pascalName,
		g.pascalName,
		g.name,
		g.pascalName,
		g.pascalName,
		g.pascalName,
		g.pascalName,
		g.snakeName,
		g.pascalName,
		g.pascalName,
		g.pascalName,
		g.pascalName,
		g.pascalName,
	)

	path := filepath.Join("app/ent/schema", g.snakeName+".go")
	return os.WriteFile(path, []byte(content), 0644)
}

/*
 * GenerateAll generates the schema.
 */
func (g *EntGenerator) GenerateAll() error {
	return g.GenerateSchema()
}
